### ISSUE TITLE
Building node with debug symbols enabled

### ISSUE THREAD

**Issue by ggkitsas** [nxhack/openwrt-node-packages#152]
Hello,

I am trying to build node with debug symbols enabled, using your package. I am changing your Makefile by adding `--debug` at `CONFIGURE_ARGS`. 

The build results in an error stating that the `execinfo.h` is missing. The `execinfo.h` is part of the glibc library. Any ideas on how to configure for linking against glibc? 

Thanks in advance.

**Comment by nxhack** [comment]
Hi @ggkitsas 

"Debug Build" is supported.  (check "Debug build" option at "make menuconfig".)
The file size of "node_g" not stripped is very huge. ;) 436MB
