### ISSUE TITLE
Please add homebridge-hue

### ISSUE THREAD

**Issue by tkso1997** [nxhack/openwrt-node-packages#1805]
Please add the Homebridge-hue plugin 

[https://www.npmjs.com/package/homebridge-hue](https://www.npmjs.com/package/homebridge-hue)

**Comment by nxhack** [comment]
Hi @tkso1997 

The build is ready. I do not have a philips hue and hue gateway. Can you please test it working?

BTW, the author is in the process of refactoring it and I will respond when "homebridge-hue2" is released.

**Comment by tkso1997** [comment]
Hi @nxhack!

Thx a lot it works perfectly!!!
