### ISSUE TITLE
Please add homebridge-tuya-platform

### ISSUE THREAD

**Issue by tkso1997** [nxhack/openwrt-node-packages#1914]
Hi, are you able to add https://github.com/iRayanKhan/homebridge-tuya? Thanks!

**Comment by nxhack** [comment]
Hi @tkso1997 

I developed it and confirmed that it works with homebridge web UI.
Please test it.
https://github.com/nxhack/openwrt-node-packages/tree/master/node-homebridge-tuya

The opkg package is currently being built.

**Comment by tkso1997** [comment]
Works! Thx a lot!
