### ISSUE TITLE
official homebridge-tuya-platform plugin

### ISSUE THREAD

**Issue by tkso1997** [nxhack/openwrt-node-packages#1932]
I recently asked for https://github.com/iRayanKhan/homebridge-tuya which you did an which works, so thanks for it!!
Unfortunately some of my devices will only work with the official plugin from the Tuya developers.

so would you be able to add https://www.npmjs.com/package/homebridge-tuya-platform? Thanks!
Sources are under:
https://github.com/tuya/tuya-homebridge

**Comment by nxhack** [comment]
Hi @tkso1997 

I have confirmed that it works with the homebridge web UI.
Please test it.
https://github.com/nxhack/openwrt-node-packages/tree/master/node-homebridge-tuya-platform

The opkg package has also been ready.

**Comment by tkso1997** [comment]
Thx a lot - works as expected!! :)
