### ISSUE TITLE
Please add homebridge-shelly-ds9

### ISSUE THREAD

**Issue by tkso1997** [nxhack/openwrt-node-packages#1936]
Please add homebridge-shelly-ds9-1.1.1 (https://www.npmjs.com/package/homebridge-shelly-ds9)
Source: https://github.com/cubi1337/homebridge-shelly-ds9

thx al lot!

**Comment by nxhack** [comment]
Hi @tkso1997 

I have confirmed that it works with the homebridge web UI.
There is a problem with the "Set Up" icon not showing up occasionally.

Please test it.
https://github.com/nxhack/openwrt-node-packages/tree/master/node-homebridge-shelly-ds9

**Comment by tkso1997** [comment]
Works like expected! Thx!
