### ISSUE TITLE
Shelly PlusUni homebridge

### ISSUE THREAD

**Issue by Cime83** [nxhack/openwrt-node-packages#1947]
I want to use a Shelly PlusUni for my garage door opener.

Does anybody know, how to get it recognized by homebridge?

Thanks for your support.
Joachim

**Comment by nxhack** [comment]
I am not familiar with 'Shelly'.

@tkso1997 Any opinions?

**Comment by tkso1997** [comment]
Don't have a PlusUni device so I can't tell. I would suggest @Cime83 to ask in https://github.com/alexryd/homebridge-shelly-ng for advice.

**Comment by Cime83** [comment]
@nxhack & @tkso1997 thanks that you looked into that topic. I will try to get support directly at the plugin-page.
