### ISSUE TITLE
Please add homebridge-xiaomi-roborock-vacuum

### ISSUE THREAD

**Issue by tkso1997** [nxhack/openwrt-node-packages#1968]
Please add the plugin for Xiaomi/Roborock vacuum cleaners 

GitHub:
https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum

NPM:
https://www.npmjs.com/package/homebridge-xiaomi-roborock-vacuum?activeTab=versions

**Comment by nxhack** [comment]
Hi @tkso1997 

I have confirmed that it works with the homebridge web UI.

https://github.com/nxhack/openwrt-node-packages/tree/master/node-homebridge-xiaomi-roborock-vacuum

Please test it. thank you.

**Comment by tkso1997** [comment]
Works - Thx a lot again!
