### ISSUE TITLE
Distribution binary

### ISSUE THREAD

**Issue by bastup** [nxhack/openwrt-node-packages#317]
Hello nxhack, and thank you for your work!

I am making a project with the MIPS binary of node.js. I am wondering if it is possible to do a distribution binary for mips-linux of my node.js project? I am working on ar71xx and your node.js binary at the moment.

Thanks!

**Comment by nxhack** [comment]
Hi @bastup 

The goal of my custom package is to merge the necessary packages into OpenWrt 's official community package. On the official package of OpenWrt, packages of various architectures are built and released. I am working on it. Please wait a little more.

**Comment by bastup** [comment]
Great to hear, thank you nxhack!
