### ISSUE TITLE
please add node-ejdb native lib

### ISSUE THREAD

**Issue by cooboyno111** [nxhack/openwrt-node-packages#32]
https://www.npmjs.com/package/ejdb

**Comment by nxhack** [comment]
Hi @cooboyno111 
Please check. I have not run tests. Please tell me result.

for CC:   https://github.com/nxhack/openwrt-node-packages/tree/for-15.05/node-ejdb
for LEDE: https://github.com/nxhack/openwrt-node-packages/tree/master/node-ejdb

**Comment by cooboyno111** [comment]
@nxhack
npm ERR! code EINTEGRITY
npm ERR! sha1-DCi8ZpqFFiFwm/eghQMDS+44ErY= integrity checksum failed when using sha1: wanted sha1-DCi8ZpqFFiFwm/eghQMDS+44ErY= but got sha1-/5Lez6nmEQwA0qEMsl9CUbaReJg=. (1615252 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     /media/lup/22e7aa1c-9dd5-4d35-ad44-7bfed156fb0d/mtklinkkit/openwrt/staging_dir/host/share/node/npm-cache/_logs/2017-07-28T08_57_00_661Z-debug.log
Makefile:63: recipe for target '/media/lup/22e7aa1c-9dd5-4d35-ad44-7bfed156fb0d/mtklinkkit/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/node-ejdb-1.2.12-42/.built' failed
for openwrt CC

**Comment by nxhack** [comment]
@cooboyno111 
Does it work well?

**Comment by cooboyno111** [comment]
@nxhack MT7628/MT7620 work well
root@k-wifi:/tmp# cat /proc/cpuinfo
system type		: MediaTek MT7628AN ver:1 eco:2
machine			: KunTeng ZC9525A
processor		: 0
cpu model		: MIPS 24KEc V5.5
BogoMIPS		: 380.92
wait instruction	: yes
microsecond timers	: yes
tlb_entries		: 32
extra interrupt vector	: yes
hardware watchpoint	: yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0ffb, 0x0ffb]
isa			: mips1 mips2 mips32r1 mips32r2
ASEs implemented	: mips16 dsp
shadow register sets	: 1
kscratch registers	: 0
package			: 0
core			: 0
VCED exceptions		: not available
VCEI exceptions		: not available

root@k-wifi:/tmp# node t.js 
Grenny OID: 597ee11a0cfef12400000000
Bounty OID: 597ee11a0cfef12400000001
Found 1 parrots
Grenny likes toys!
use https://www.npmjs.com/package/ejdb test。
Ejdblib takes up 1.5M of space
