### ISSUE TITLE
BAD NEWS: remove mips support 

### ISSUE THREAD

**Issue by nxhack** [nxhack/openwrt-node-packages#464]
Upstream of node.js, support for mips seems to be removed in the future. I plan to maintain mips as much as possible but may not be able to do so depending on the circumstances.

https://github.com/nodejs/node/issues/26179
https://github.com/nodejs/node/pull/26192

**Comment by nxhack** [comment]
The mips support has been removed in v12.0.0.
I'm reverting the deleted codes.

**Comment by nxhack** [comment]
Modules that will break in Node 12

node-authenticate-pam
node-bignum
node-bleacon
node-bluetooth-hci-socket
node-ejdb
node-ffi
node-fuse-bindings
node-hashtable
node-mdns
node-mknod
node-modbus
node-net-ping 
node-node-expat
node-node-hid
node-node-hid-stream
node-node-red-contrib-modbus
node-openzwave-shared
node-pi-spi
node-rpio
node-sleep
node-sqlite3
node-serialport-bindings
  node-serialport
  node-arduino-firmata	
  node-firmata
  node-johnny-five
  node-node-enocean-utils

**Comment by nxhack** [comment]
The cross compilation environment is broken in v12.5.0.
The situation is difficult.

**Comment by nxhack** [comment]
@p3x-robot 
As it was likely to take time to support v12.5.0, I made a dedicated branch. For that purpose, I restored the master branch and the development branch.
It is the latest version that v12.4.0 is supported.

**Comment by nxhack** [comment]
build: add mips64el support

https://github.com/nodejs/node/pull/27992

**Comment by nxhack** [comment]
Exactly.
mips32 will not be considered much.
I will try my best as much as possible.

**Comment by nxhack** [comment]
After v8-7.9, mips(eb) and mips64(eb) will not work.

**Comment by alenteria** [comment]
I successfully compiled nodejs v10 for mipsel_24kc (newifi D2).
But the only problem I have right now is it's really slow. CPU and ram consumptions are at less than 50% only. Simple http ajax request, express response at 2-3 seconds.

**Comment by nxhack** [comment]
Verified with version 14.12.0. Unfortunately, I confirmed that it does not work on mips(eb) and mips64(eb).
