### ISSUE TITLE
Node-Red stuck on startup

### ISSUE THREAD

**Issue by salmanisd** [nxhack/openwrt-node-packages#465]
Hello...
I built the latest Node-Red version and installed it on my router with MIPS 24KEc.
If i start it with typing `node-red` on the terminal, i get 
```
Welcome to Node-RED
===================

25 Feb 10:22:45 - [info] Node-RED version: v0.19.5
25 Feb 10:22:45 - [info] Node.js  version: v8.10.0
25 Feb 10:22:45 - [info] Linux 4.14.95 mipsel LE

```

and thats it.It doesn't proceed further and I cannot also reach the node-red UI  through my PC.
Can't find any logs and dont know how to debug this issue. 

edit:
I killed the npm command process i saw in `ps` and the output moved a little ahead. now its stuck at
```
Welcome to Node-RED
===================

25 Feb 10:22:45 - [info] Node-RED version: v0.19.5
25 Feb 10:22:45 - [info] Node.js  version: v8.10.0
25 Feb 10:22:45 - [info] Linux 4.14.95 mipsel LE
25 Feb 11:22:59 - [info] Palette editor disabled : npm command not found
25 Feb 11:22:59 - [info] Loading palette nodes
```

**Comment by nxhack** [comment]
Hi @salmanisd 
```
25 Feb 11:22:59 - [info] Palette editor disabled : npm command not found
```
The npm command is a separate package(node-npm). What happens after installing the npm package?

**Comment by nxhack** [comment]
I will correct the dependency of npm in the node-red package.

**Comment by salmanisd** [comment]
> Hi @salmanisd
> 
> ```
> 25 Feb 11:22:59 - [info] Palette editor disabled : npm command not found
> ```
> 
> The npm command is a separate package(node-npm). What happens after installing the npm package?

The npm package is already installed
```
root@OpenWrt:~# npm -v
5.6.0
```
Although it took more than 40 secs wait just to display the npm version.

**Comment by nxhack** [comment]
Hi @salmanisd 

> Although it took more than 40 secs wait just to display the npm version.

Oh! 40 secs...

(I think that you already know...)
Is there enough memory?
Is there enough CPU power?

And... Please change the settings etc. often pointed out when the operation of npm is slow.
```
npm set progress=false
npm config set registry http://registry.npmjs.org/
```

**Comment by salmanisd** [comment]
Hi 

I changed npm settings like you suggested but no effect. I guess the MIPS CPU I have on the router is just not able to run node-red successfully.
Thanks for your help.
