### ISSUE TITLE
Chaos Calmer(15.05) still not supported?

### ISSUE THREAD

**Issue by The-Alchemist** [nxhack/openwrt-node-packages#5]
I was wondering what it would take to support Chaos Calmer.  The README says it's not supported.

Thanks!

**Comment by nxhack** [comment]
@The-Alchemist 

Tested for Chaos Calmer. But for some reason only node.js v4.x.

https://github.com/nxhack/openwrt-node-packages/tree/for-15.05

**Comment by The-Alchemist** [comment]
Thanks so much!

**Comment by nxhack** [comment]
v6.x & upper, build fail in case of using uclibc and gcc(g++) 4.8. You should apply patch on gcc package.

https://github.com/artynet/openwrt-git/blob/openwrt-1505-setup-03/toolchain/gcc/patches/4.8-linaro/852-libstdcxx-uclibc-c99.patch

**Comment by nxhack** [comment]
and also apply patches on uclibc package.

https://github.com/artynet/openwrt-git/blob/openwrt-1505-setup-03/toolchain/uClibc/patches-0.9.33.2/L001-uClibc-add-execvpe-function.patch
https://github.com/artynet/openwrt-git/blob/openwrt-1505-setup-03/toolchain/uClibc/patches-0.9.33.2/L002-libm_Add_missing_C99_float_ld_wrappers.patch
https://github.com/artynet/openwrt-git/blob/openwrt-1505-setup-03/toolchain/uClibc/patches-0.9.33.2/L003-force-obstack-free-strong-alias.patch

**Comment by ZackMattor** [comment]
@The-Alchemist have you been able to compile for v6 or v7?

**Comment by The-Alchemist** [comment]
@ZackMattor : Sorry, I'm short on time.  I haven't tried. :(

**Comment by ZackMattor** [comment]
Alright, well we're working on it. I'll report back here if we get it. Might have some questions @nxhack 😉

**Comment by ZackMattor** [comment]
@The-Alchemist not sure if you care anymore... But we seem to have it building, Master open-wrt and node v7.5.0 ;)

**Comment by The-Alchemist** [comment]
@ZackMattor : That's excellent news!  I'm super excited!   Do you remember how big it was?

I'm hoping to be able to stick it on a 32MB Omega2+.

**Comment by ZackMattor** [comment]
@The-Alchemist It will definitely fit within 32mb! The total size we ended up with before trimming stuff was 17mb for the whole image (1mb outside of our flash) by removing some unneeded stuff we got it below. I think the node size was around 6mb.

**Comment by cooboyno111** [comment]
If you don't need icu&i18n .
you can remove DEPENDS "+NODEJS_ICU:icu"
rom size 10m+。

**Comment by artynet** [comment]
@ZackMattor @cooboyno111 please rebuild the toolchain with the above patches and then build the node packages :

https://github.com/artynet/openwrt-git/blob/openwrt-1505-setup-04/package/linino/node/Makefile
https://github.com/artynet/openwrt-git/blob/openwrt-1505-setup-04/package/linino/node7/Makefile

Best, Arturo

**Comment by cooboyno111** [comment]
I successfully compiled nodejs6. on Chaos Calmer(15.05) . You need to change toolchain from uclibc0.9 to uclibc-ng 1.0.6. You need to remove ICU support. The librpc version of the library that needs to be modified is 2015-11-04.

**Comment by artynet** [comment]
@cooboyno111 the L00X patches are needed to add those functionalities to the legacy version of uClibc. I have also the patches to build the latest release of node v8 as well 👍 

https://github.com/artynet/openwrt-git/tree/openwrt-1505-setup-04/package/linino/node8/patches

take a look at the link above ;)

Best, Arturo

**Comment by cooboyno111** [comment]
@artynet I'm going to test your patch. But I think uclibc 0.99 is too old.

**Comment by nxhack** [comment]
for-15.05 branch updated. 

Aggregated the necessary patches for build latest node.js version .
https://github.com/nxhack/openwrt-node-packages/blob/for-15.05/for_building_latest_node.patch

These patches are based on the work of the OpenWrt/LEDE developers and the buildroot developers and @artynet
