### ISSUE TITLE
Languages > Node.js folder Empty

### ISSUE THREAD

**Issue by sunzongzheng** [nxhack/openwrt-node-packages#519]
![image](https://user-images.githubusercontent.com/12635613/58619030-8e270b80-82f6-11e9-8cca-64bcd928675e.png)
Why empty? I can not choose one version to compile.

**Comment by nxhack** [comment]
Probably You don't use openwrt 18.06 version upper, or it's an unsupported CPU ARCH.

Support for the old openwrt has been dropped to support the latest node.js.

Please consider using this:  https://github.com/nxhack/openwrt-node-packages/tree/for-15.05
(not updated frequently)

**Comment by sunzongzheng** [comment]
I run it on wsl. ubuntu 16.04 
![image](https://user-images.githubusercontent.com/12635613/58622164-920a5c00-82fd-11e9-8a91-c2cab902b390.png)

Can i do a cross compilation? I can not change the target system after pressing enter
![image](https://user-images.githubusercontent.com/12635613/58622854-3771ff80-82ff-11e9-98ba-d9e1c89a8c68.png)

**Comment by nxhack** [comment]
Please read : https://openwrt.org/docs/guide-developer/build-system/use-buildsystem

**Comment by nxhack** [comment]
And  Please read : https://github.com/nxhack/openwrt-node-packages#illegal-instruction-issue

**Comment by nxhack** [comment]
And : https://forum.openwrt.org/t/fun-project-build-lede-using-bash-on-ubuntu-on-windows-wsl-windows-subsystem-for-linux/3819

**Comment by nxhack** [comment]
And : https://github.com/Microsoft/WSL/issues/432

**Comment by nxhack** [comment]
I recommend using VirtualBox.

**Comment by nxhack** [comment]
I will close the issue. Don't hesitate to reopen it if you still have the issue.
