### ISSUE TITLE
Cannot find Homebridge in iOS Home app

### ISSUE THREAD

**Issue by NN708** [nxhack/openwrt-node-packages#526]
I am using OpenWrt 18.06.2 on Netgear R6220, with FPU emulator enabled. I compiled OpenWrt with node, node-npm, node-hap-nodejs, node-homebridge and avahi-dbus-daemon. However, after installation, I cannot find Homebridge in my iOS Home app.
I run `logread | fgrep homebridge` and `logread | fgrep avahi-daemon`. It seems that they are working normally:
```
root@OpenWrt:~# logread | fgrep homebridge
daemon.err homebridge[1590]: npm info it worked if it ends with ok
daemon.err homebridge[1590]: npm info using npm@6.9.0
daemon.err homebridge[1590]: npm info using node@v10.16.0
daemon.err homebridge[1590]: npm timing npm Completed in 13741ms
daemon.err homebridge[1590]: npm info ok
daemon.err homebridge[1590]: config.json (/usr/share/homebridge/config.json) not found.
daemon.err homebridge[1590]: No plugins found. See the README for information on installing plugins.
daemon.info homebridge[1590]: Setup Payload:
daemon.info homebridge[1590]: X-HM://0023*********
daemon.info homebridge[1590]: Scan this code with your HomeKit app on your iOS device to pair with Homebridge: *****
daemon.info homebridge[1590]: Or enter this code with your HomeKit app on your iOS device to pair with Homebridge: ***-**-***
daemon.info homebridge[1590]: Homebridge is running on port *****.
```

```
daemon.info avahi-daemon[1064]: Found user 'nobody' (UID *****) and group 'nogroup' (GID *****).
daemon.info avahi-daemon[1064]: Successfully dropped root privileges.
daemon.info avahi-daemon[1064]: avahi-daemon 0.6.32 starting up.
daemon.warn avahi-daemon[1064]: WARNING: No NSS support for mDNS detected, consider installing nss-mdns!
daemon.info avahi-daemon[1064]: No service file found in /etc/avahi/services.
daemon.info avahi-daemon[1064]: Network interface enumeration completed.
daemon.info avahi-daemon[1064]: Registering HINFO record with values 'MIPS'/'LINUX'.
daemon.info avahi-daemon[1064]: Server startup complete. Host name is OpenWrt.local. Local service cookie is **********.
daemon.info avahi-daemon[1064]: Joining mDNS multicast group on interface br-lan.IPv4 with address 192.168.1.1.
daemon.info avahi-daemon[1064]: New relevant interface br-lan.IPv4 for mDNS.
daemon.info avahi-daemon[1064]: Registering new address record for 192.168.1.1 on br-lan.IPv4.
daemon.info avahi-daemon[1064]: Joining mDNS multicast group on interface eth0.IPv6 with address fe80::12da:43ff:****:****.
daemon.info avahi-daemon[1064]: New relevant interface eth0.IPv6 for mDNS.
daemon.info avahi-daemon[1064]: Registering new address record for fe80::12da:43ff:****:**** on eth0.*.
daemon.info avahi-daemon[1064]: Joining mDNS multicast group on interface eth0.2.IPv6 with address fe80::12da:43ff:****:****.
daemon.info avahi-daemon[1064]: New relevant interface eth0.2.IPv6 for mDNS.
daemon.info avahi-daemon[1064]: Registering new address record for fe80::12da:43ff:****:**** on eth0.2.*.
daemon.info avahi-daemon[1064]: Joining mDNS multicast group on interface br-lan.IPv6 with address fe80::12da:43ff:****:****.
daemon.info avahi-daemon[1064]: New relevant interface br-lan.IPv6 for mDNS.
daemon.info avahi-daemon[1064]: Registering new address record for fe80::12da:43ff:****:**** on br-lan.*.
daemon.info avahi-daemon[1064]: Leaving mDNS multicast group on interface br-lan.IPv6 with address fe80::12da:43ff:****:****.
daemon.info avahi-daemon[1064]: Joining mDNS multicast group on interface br-lan.IPv6 with address fd25:****:****::1.
daemon.info avahi-daemon[1064]: Registering new address record for fd25:****:****::1 on br-lan.*.
daemon.info avahi-daemon[1064]: Withdrawing address record for fe80::12da:43ff:****:**** on br-lan.
daemon.info avahi-daemon[1064]: Joining mDNS multicast group on interface wlan0.IPv6 with address fe80::12da:43ff:****:****.
daemon.info avahi-daemon[1064]: New relevant interface wlan0.IPv6 for mDNS.
daemon.info avahi-daemon[1064]: Registering new address record for fe80::12da:43ff:****:**** on wlan0.*.
daemon.info avahi-daemon[1064]: Joining mDNS multicast group on interface wlan1.IPv6 with address fe80::12da:43ff:****:****.
daemon.info avahi-daemon[1064]: New relevant interface wlan1.IPv6 for mDNS.
daemon.info avahi-daemon[1064]: Registering new address record for fe80::12da:43ff:****:**** on wlan1.*.
```
I also tested the connection with Homebridge port and the port was open. Then I checked with `avahi-browse -at` and found out that there were nothing about Homebridge.
However, my Raspberry Pi can still run Homebridge normally. What’s the problem? Did I omit any required packages?

**Comment by nxhack** [comment]
Hi @NN708 

Does homebridge bind with the intended interface?

please check.
```
opkg update
opkg install avahi-utils
avahi-browse -t _hap._tcp
```

**Comment by NN708** [comment]
It returns nothing. What should I do to bind with the interface?

**Comment by nxhack** [comment]
Can you see the QR code that homebridge outputs in logread?

**Comment by NN708** [comment]
Yes, I can. I scanned the QR code with Home app, then it was searching for accessory, but finally no accessory was found.

**Comment by nxhack** [comment]
hmm...
You should see "_hap._tcp" if homebrige is started correctly. So I think homebridge is not running.

In my test environment:
```
~ # avahi-browse -t _hap._tcp
+ br-lan IPv4 Homebridge-CAD8                               _hap._tcp            local
```
```
~ # avahi-browse -rt _hap._tcp
+ br-lan IPv4 Homebridge-CAD8                               _hap._tcp            local
= br-lan IPv4 Homebridge-CAD8                               _hap._tcp            local
   hostname = [CC_22_3D_E3_CE_30.local]
   address = [172.17.0.2]
   port = [33291]
   txt = ["sh=hJpPnw==" "sf=1" "ci=2" "ff=0" "s#=1" "c#=2" "id=CC:22:3D:E3:CE:30" "pv=1.0" "md=Homebridge"]
```

**Comment by NN708** [comment]
I run `ps | grep homebridge` and that shows it is running. Also, the port of Homebridge is seen open on another computer.

**Comment by nxhack** [comment]
hmm... It is a curious condition.
```
avahi-browse -t _hap._tcp
```
It does not work if  _hap._tcp service is not registered.

**Comment by nxhack** [comment]
Please check the simple check of avahi.
```
opkg install avahi-daemon-service-ssh
/etc/init.d/avahi-daemon restart
avahi-browse -at
```

**Comment by NN708** [comment]
There are something about OpenWrt:
```
root@OpenWrt:~# avahi-browse -at
+  wlan1 IPv6 OpenWrt                                       _ssh._tcp            local
+  wlan0 IPv6 OpenWrt                                       _ssh._tcp            local
+ br-lan IPv6 OpenWrt                                       _ssh._tcp            local
+ br-lan IPv4 OpenWrt                                       _ssh._tcp            local
+   eth0 IPv6 OpenWrt                                       _ssh._tcp            local
```

**Comment by nxhack** [comment]
It's a homebridge side problem because avahi seems to be working.

**Comment by nxhack** [comment]
Which network interface do you want to use?

> br-lan IPv4 OpenWrt

correct?

**Comment by NN708** [comment]
Yes

**Comment by NN708** [comment]
I'm trying to find the Homebridge log file. Homebridge Wiki says:
>Homebridge logs to two places:
/var/log/homebridge.log
/var/log/homebridge.err

But I can't find these files. Where are they on OpenWrt?

**Comment by nxhack** [comment]
Please try this

https://www.reddit.com/r/homebridge/comments/aiexkx/problems_connecting_homebridge_to_homekit/

**Comment by nxhack** [comment]
> But I can't find these files. Where are they on OpenWrt?

All logs are in ring buffer memory. Using logread command is the Openwrt style. :)

**Comment by NN708** [comment]
I tried to add `"mdns": {"interface": "192.168.1.1"}` to my config.json, but in `avahi-browse -a` there are still nothing. The good news is, the Home app prompts "Uncertified Accessory" now, but after I press "Add Anyway", it says "Home couldn't connect to this accessory".

**Comment by nxhack** [comment]
How about this command
```
avahi-browse -t _hap._tcp
```


Check  accessories and platforms in config.json.
Try restarting your homebridge, see below
https://github.com/nfarina/homebridge#my-ios-app-cant-find-homebridge

**Comment by NN708** [comment]
I have already read and tried it, but no use. I think the problem is that Homebridge didn't broadcast via avahi, but it didn't give out any error message...

**Comment by nxhack** [comment]
[FYI]
The default config.json path of the OpenWrt homebridge package is
```
/usr/share/homebridge/config.json
```

and The privilege to operate is "homebridge" user.

**Comment by nxhack** [comment]
check
```
/etc/avhi/avahi-daemon.conf
```
specify 
```
allow-interfaces=br-lan
``` 
https://forum.archive.openwrt.org/viewtopic.php?id=56615

**Comment by NN708** [comment]
It didn't solve the problem. And there's a warning with avahi-daemon:
```
*** WARNING: Detected another IPv4 mDNS stack running on this host. This makes mDNS unreliable and is thus not recommended. ***
```

**Comment by nxhack** [comment]
```
 killall avahi-daemon
/etc/init.d/avahi-daemon start
```

**Comment by nxhack** [comment]
Interesting... homebridge bind udp 5353

This procedure may be necessary if you want to restart avahi-daemon.
```
/etc/init.d/homebridge stop
/etc/init.d/avahi-daemon restart
/etc/init.d/homebridge start
```

**Comment by NN708** [comment]
Now the Home app can discover Homebridge on OpenWrt, so perhaps it is not the problem with avahi...
What's more, I tried to run Homebridge my Raspberry Pi again and there's no _hap._tcp in `avahi-browse -a`, but I can connect to it normally.

**Comment by nxhack** [comment]
It does not appear in "**-a**" even in my environment. Please check with "**-t _hap._tcp**"

**Comment by nxhack** [comment]
@NN708 
If possible, I hope you publish a summary of the solution.

Thank you.

**Comment by NN708** [comment]
There isn't any solution so far... Home app can only "discover" Homebridge, but can't connect to it...

**Comment by NN708** [comment]
Home app can find the accessory:
![C2D53059-BF8A-4CC3-8603-C63420DDCAB4](https://user-images.githubusercontent.com/20534082/59421817-d15aa180-8e01-11e9-982d-7d3d1f1745b8.jpeg)
Then I try to connect to it:
![55F89C9C-F447-43A2-821B-F9F66A769249](https://user-images.githubusercontent.com/20534082/59421854-e6373500-8e01-11e9-9d4b-5dfeb81db9c5.jpeg)
![7DE1F1EC-9EA5-4557-A8F0-451FF04C5455](https://user-images.githubusercontent.com/20534082/59421855-e6cfcb80-8e01-11e9-912f-df09a90d67d8.jpeg)
But failed:
![A1A9D1C3-3F0E-4D7B-BC71-852471CBEF7C](https://user-images.githubusercontent.com/20534082/59421874-efc09d00-8e01-11e9-9ada-2940902ebc2c.jpeg)
Looks like some connection issues between Home app and Homebridge...

**Comment by nxhack** [comment]
Ping youre iPhone from the OpenWrt host and check continuity.

https://www.iphonefaq.org/archives/971437

**Comment by nxhack** [comment]
This may also be useful for problem solving.

iPhone app - Discovery - DNS-SD Browser
https://apps.apple.com/us/app/discovery-dns-sd-browser/id305441017

**Comment by nxhack** [comment]
A common thing to try in case of home bridge connection problem is
disable IPv6, 
restart the router, 
disable IGMP snooping setting on the router.

**Comment by NN708** [comment]
Thank you for your suggestions. Ping is OK, and I found that when I try to connect Homebridge in my Home app, the CPU usage increases to 50% (normally it is about 2%). That indicates there’s no connection problem between iOS and Homebridge.
Now I guess, perhaps the issue is related to the low performance of my router. It takes the router more than 20 seconds to start the Homebridge process, which is normally under 5 seconds on my Raspberry Pi. If Homebridge doesn’t respond in time, the Home app may think the connection is lost.

**Comment by nxhack** [comment]
I have a similar experience. It tries to register to home.app many times and succeeds. It works well once registered.

**Comment by nxhack** [comment]
There are also problems with key generation, so can you try it?
```
opkg install haveged
```

**Comment by NN708** [comment]
I tried to use haveged, but it didn’t solve the problem.

**Comment by nxhack** [comment]
I tested with my home router.

CPU: QCA9563 @ 775 MHz
Mem: 128MB

I have run homebridge in debug mode.
As a result, connected to HAPServer from the iOS side and found that the session timed out while homebridge was generating a key pair.

It seems to be a specification on the iOS side.
https://developer.apple.com/documentation/foundation/nsurlsessionconfiguration/1408259-timeoutintervalforrequest?language=objc

homebridge works fine with raspberry pi zero w + openwrt (head).
Also it worked in the past with AR9331 400MHz 64MB. (lede-17.01, node-v6, homebridge[unknown old version])

**Comment by NN708** [comment]
I found that the problem also exists in pairing with accessories (using plugin). The pairing timed out on OpenWrt, but works fine on Raspberry Pi.

**Comment by NN708** [comment]
I also tried to pair on Raspberry Pi first, and then copy Homebridge /persist files to OpenWrt, but it didn’t work.

**Comment by nxhack** [comment]
Stop using the avahi package and I will try "mdnsresponder" package or "umdns" package.
It will take some time to test.

**Comment by nxhack** [comment]
It seems that there has been a change in hap-nodejs. The old precompiled binary module is no longer used. There seems to be a difference in performance.


https://github.com/KhaosT/HAP-NodeJS/commit/47966d13cfea35ce7acb4b0780faaae745eef69c#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
https://github.com/KhaosT/HAP-NodeJS/commit/2a66d6fa58a51ae87346dfcae063696d0352b47f#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

**Comment by NN708** [comment]
So we have to compile TweetNaCl.js first?

**Comment by nxhack** [comment]
Changed to be able to select the old hap-nodejs module. (I have not tested it in my environment yet.)

https://github.com/nxhack/openwrt-node-packages/blob/master/node-hap-nodejs/Makefile

**Comment by NN708** [comment]
OK, I will try it later.

**Comment by NN708** [comment]
I tried HAP-NodeJS 0.4.49, but it has the same problem.

**Comment by nxhack** [comment]
I tested on raspberry pi zero w with openwrt head and homebridge of community package, but I could connect easily.
As you may have guessed it is a problem with floating point computing power at key generation.

I will mention in README.md that it often does not work in environments where mips fpu emu is used.

**Comment by nxhack** [comment]
I will close the issue. Don't hesitate to re-open it if you still have the issue.

**Comment by nature2608** [comment]
I have the same problems like yours,i used [homekit-bridge](https://github.com/NRCHKB/node-red-contrib-homekit-bridged/issues/191),have you successfuly run it in openwrt? @NN708 
I have tried run it on ar9558 and mt7621 devices,but it still can not be connected.

**Comment by NN708** [comment]
Sadly, no. I’m using my Raspberry Pi instead.

**Comment by nature2608** [comment]
what a shame.I still can not figure out why after trying so many ways.
