### ISSUE TITLE
package configuration menu is empty

### ISSUE THREAD

**Issue by deaddy64** [nxhack/openwrt-node-packages#586]
Hello. 
I'm trying to check your fix #571 , but after updating feed i have an empty list in "Node.js" dir of menuconfig. So can't choose node version. Nothing changes after feeds update and install.
Has anything changed in feed index? Or i do something wrong?

**Comment by nxhack** [comment]
Hi @deaddy64 

Check if MIPS_FPU_EMULATOR is enabled.
https://github.com/nxhack/openwrt-node-packages/tree/lede-17.01#illegal-instruction-issue

**Comment by deaddy64** [comment]
In my make menuconfig i have no "MIPS_FPU_EMULATOR"
![image](https://user-images.githubusercontent.com/2561233/63565595-4b06cc80-c5b5-11e9-9bf3-ca721c1d2b16.png)
I have this option only in kernel_menuconfig. I've selected it.
![image](https://user-images.githubusercontent.com/2561233/63565736-e6983d00-c5b5-11e9-9a29-0a9a3fbcf58e.png)
But there is still empty list in Node dir of menuconfig. Then i edited DEPENDS of Makefile: add "||y" to the first expression. Finally it's ok now!
But the question remained. It seems that KERNEL_MIPS_FPU_EMULATOR option is not defined even if it was selected in kernel_menuconfig.
![image](https://user-images.githubusercontent.com/2561233/63565957-e9dff880-c5b6-11e9-9ee5-f6d41f4ccca3.png)
Thnx.

**Comment by nxhack** [comment]
Oh!!!

lede-17.01 did not have that setting.
I applied the patch myself, so I made a mistake.

I will change it as soon as possible.

**Comment by nxhack** [comment]
@deaddy64 

Fixed.
Thank you for the report.
