### ISSUE TITLE
need npm version upgrade due existing bug

### ISSUE THREAD

**Issue by deaddy64** [nxhack/openwrt-node-packages#589]
I'm trying to compile node-serialport-bindings module and getting a error:
```
npm info using npm@6.9.0
npm info using node@v10.16.3
npm timing stage:loadCurrentTree Completed in 18ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 1ms
npm timing stage:rollbackFailedOptional Completed in 0ms
npm timing stage:runTopLevelLifecycles Completed in 45ms
npm ERR! Cannot read property 'resolve' of undefined
```
It seems that there is a error in this npm version [https://github.com/nodejs/help/issues/1941](url)
Is it possible to upgrade npm to the latest version (6.11) when compiling node? How can i do this? thnx.

**Comment by nxhack** [comment]
Please wait until the upstream takes action.

**Comment by nxhack** [comment]
bump  v10.17.0 (update npm to 6.11.3)

**Comment by nxhack** [comment]
I will close the issue. Don't hesitate to re-open it if you still have the issue.
