### ISSUE TITLE
vocore2 GPIO support

### ISSUE THREAD

**Issue by Nickman87** [nxhack/openwrt-node-packages#600]
Hi,

I was wondering if your libraries might be used to access the GPIO pins on the voCore2?
My voCore is still on it's way so I cannot test right now, but maybe somebody could give me some more information?

Thanks!

**Comment by nxhack** [comment]
You can open an issue here. Patches are also welcome.

https://github.com/intel-iot-devkit/mraa/issues

**Comment by nxhack** [comment]
I will close the issue. Don't hesitate to re-open it if you still have the issue.
