### ISSUE TITLE
Node Red not listed in System/Startup

### ISSUE THREAD

**Issue by sans-ltd** [nxhack/openwrt-node-packages#680]
In `node-red/files/node-red.init` the line
`START=99`
is missing. Would be great if somebody could add it. I would do it on myself but I currently do not have the permissions to do so. 
Another good thing would be to run node-red as a separate user with a special home directory (e.g. under `/var/lib/node-red`) because for some node-red applications it is sometimes necessary to make modifications in `$HOME/.node-red`
It is not nice that this is currently `/root/.node-red` especially when the full application should be packaged later in development.
In addition, running such a complex application as root is a big security threat.
I could help to achieve this, if you like.

**Comment by BKPepe** [comment]
ping @ja-pa as he added init script

**Comment by nxhack** [comment]
Sorry for the delay in responding, fix.

# The coronavirus has prevented me from responding to you as usual...
