### ISSUE TITLE
Illegal instruction

### ISSUE THREAD

**Issue by xhorak** [nxhack/openwrt-node-packages#7]
Any hint why I'm getting:

``root@OpenWrt:~# node``
``Illegal instruction``

Using `src-git node https://github.com/nxhack/openwrt-node-packages.git;for-15.05` as a feed. For example mosquito I've also build runs fine.

**Comment by nxhack** [comment]
@xhorak 
Are you running nodejs on AR9331? If so, please look at this thread.
https://github.com/openwrt/packages/issues/2633

**Comment by nxhack** [comment]
**Illegal instruction issue**
If you are running nodejs on Atheros AR933x, You need to make a kernel with CONFIG_MIPS_FPU_EMULATOR=y.
