### ISSUE TITLE
OpenWrt 21.02 and HEAD drop KERNEL_MIPS_FPU_EMULATOR

### ISSUE THREAD

**Issue by nxhack** [nxhack/openwrt-node-packages#736]
In the latest version of OpenWrt, support for MIPS FPU emulators has disappeared. 
This removes mips(eb,el) and mips64(eb,el) from the active list.

https://github.com/openwrt/openwrt/commit/ac5671f46cb4a300e2a8ae00db70c248828367f5

**Comment by nxhack** [comment]
linux kernel 5.x drop this option.
OpenWrt-18.06 linux-4.14 has this option.

Anyway, the development branch does not support mips.

**Comment by predators46** [comment]
{standard input}: Assembler messages:
{standard input}:126: Error: opcode not supported on this processor: mips32r2 (mips32r2) `ldc1 $f0,24($fp)'
{standard input}:127: Error: opcode not supported on this processor: mips32r2 (mips32r2) `mtc1 $t0,$f1'
{standard input}:128: Error: opcode not supported on this processor: mips32r2 (mips32r2) `sdc1 $f0,24($fp)'
