### ISSUE TITLE
error: 'uv_library_shutdown' was not declared in this scope

### ISSUE THREAD

**Issue by itProfi** [nxhack/openwrt-node-packages#775]
Good day! When compile form source openwrt 19.07  - under Debian 10 i always try this error:
````../src/api/environment.cc: In function 'void node::DefaultProcessExitHandler(node::Environment*, int)':
../src/api/environment.cc:712:3: error: 'uv_library_shutdown' was not declared in this scope
   uv_library_shutdown();
   ^~~~~~~~~~~~~~~~~~~
../src/api/environment.cc:712:3: note: suggested alternative: 'uv_shutdown'
   uv_library_shutdown();
   ^~~~~~~~~~~~~~~~~~~
   uv_shutdown
make[5]: *** [libnode.target.mk:223: /home/iobroker/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/node-v14.15.1/out/Release/obj.target/libnode/src/api/environment.o] Error 1
make[4]: *** [Makefile:104: node] Error 2
make[4]: Leaving directory '/home/iobroker/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/node-v14.15.1'
make[3]: *** [Makefile:200: /home/iobroker/openwrt/build_dir/target-arm_cortex-a9+neon_musl_eabi/node-v14.15.1/.built] Error 2
make[3]: Leaving directory '/home/iobroker/openwrt/feeds/node/node'
time: package/feeds/node/node/compile#40.91#6.13#48.69
make[2]: *** [package/Makefile:113: package/feeds/node/node/compile] Error 2
make[2]: Leaving directory '/home/iobroker/openwrt'
make[1]: *** [package/Makefile:107: /home/iobroker/openwrt/staging_dir/target-arm_cortex-a9+neon_musl_eabi/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/iobroker/openwrt'
make: *** [/home/iobroker/openwrt/include/toplevel.mk:227: world] Ошибка 2
````
All libraries is installed, all feeds are updated...
Same problem and on Node 12...

**Comment by nxhack** [comment]
Check feeds.conf. Probably the packages feed of 19.07.4 has an older version of libuv.

Change the relevant line to this if possible.
```
rc-git packages https://git.openwrt.org/feed/packages.git;openwrt-19.07
```

If I get more issues of this kind, I will make changes to my node package.

**Comment by itProfi** [comment]
> Check feeds.conf. Probably the packages feed of 19.07.4 has an older version of libuv.
> 
> Change the relevant line to this if possible.
> 
> ```
> rc-git packages https://git.openwrt.org/feed/packages.git;openwrt-19.07
> ```
> 
> If I get more issues of this kind, I will make changes to my node package.

I use this line in feeds.conf

**Comment by nxhack** [comment]
This was not the case?
```
src-git packages https://git.openwrt.org/feed/packages.git^eae1bb397f064befe003b01a36ae318321e81d35
```

**Comment by itProfi** [comment]
I try build opewrt for this branche - https://github.com/devbis/openwrt/tree/lumi-19.07
This my feeds.conf
```
src-git packages https://git.openwrt.org/feed/packages.git^eae1bb397f064befe003b01a36ae318321e81d35
src-git luci https://git.openwrt.org/project/luci.git^0d0ab01a64f25d15325d3c98a7df252085382f1d
src-git routing https://git.openwrt.org/feed/routing.git^b77498bd56d5e45ab4577a1f4ad6ffc55b4a86b7
src-git telephony https://git.openwrt.org/feed/telephony.git^91b34e7eefa1d37a18390d0c6881978cd76804a1
src-git node https://github.com/nxhack/openwrt-node-packages.git;openwrt-19.07
````
Maybe this reason?

**Comment by nxhack** [comment]
"packages" line.

Since there seems to be a lot of issues, I'll just fix my 19.07 branch for now.

Please be patient, I will fix my 19.07 branch.

**Comment by nxhack** [comment]
same : https://github.com/nxhack/openwrt-node-packages/issues/758

**Comment by nxhack** [comment]
Fixed.
 Set shared-libuv to disable.

@itProfi  test please.

**Comment by itProfi** [comment]
> Fixed.
> Set shared-libuv to disable.
> 
> @itProfi test please.

All works fine! Thanks!
![Скриншот 27-11-2020 143623](https://user-images.githubusercontent.com/6728198/100445433-248be700-30be-11eb-9bed-b25a4c0d1fa6.jpg)
