### ISSUE TITLE
Branch for OpenWrt 21.02

### ISSUE THREAD

**Issue by BKPepe** [nxhack/openwrt-node-packages#847]
Hi,

Are you planning to create branch for upcoming OpenWrt 21.02 release?

Looking forward to hearing from you,
Josef

**Comment by nxhack** [comment]
@BKPepe 

Yes, it is. I'm currently working on the 21.02 build environment (all supported targets), which isn't stable yet due to many fixes to master and 21.02 itself. I'm going to create a 21.02 branch for now, but it's not stable yet. Please wait a little longer.

**Comment by BKPepe** [comment]
I see it was created, thank you so much! I'm closing this.
