### ISSUE TITLE
Pre compiled

### ISSUE THREAD

**Issue by scenaristeur** [nxhack/openwrt-node-packages#95]
Is there a repo where we can download precompiled image, to test . 
Thx

**Comment by nxhack** [comment]
Hi @scenaristeur 
The node v6.x is supported in the LEDE project now. [Here](http://downloads.lede-project.org/) you will find packages of various architectures. If there is a necessary 'native module', I will try to put new node modules into the official package of LEDE.

**Comment by scenaristeur** [comment]
thxs, i'll try ;-)

**Comment by radiolee** [comment]
@nxhack what's the name of node package in LEDE?

**Comment by nxhack** [comment]
Hi @radiolee 
```
opkg update
opkg list|grep ^node
```
I will add what I need in my custom packages to the  official OpenWrt packages.
It takes time since my Pull Request is not merged quickly.

**Comment by radiolee** [comment]
@nxhack  thanks , I can't find node* before because it's a release version source. finally it's here for ar71xx: http://downloads.openwrt.org/snapshots/packages/mips_24kc/packages/
